# Bilingual Exam Data Generator (English-Telugu)

This notebook generates sample exam data in both English and Telugu languages for the EAMCET online examination platform. Each question and answer will contain text in English followed by a newline and then Telugu translation.

## Purpose

- Create structured exam data with bilingual support
- Format questions and answers according to the required pattern
- Generate Excel files that can be imported into the examination system
- Support multiple sections with different question types

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import random
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
import datetime

## 2. Create Sample Data Structure

We'll define the structure for our bilingual exam data. Each record will contain:
- Question ID
- Section name
- Question text in English and Telugu
- Four options (A, B, C, D) in both languages
- Correct answer

In [2]:
# Define sections
sections = ["Mathematics", "Physics", "Chemistry"]

# Create empty lists to store data
question_id = []
section_name = []
question_text = []
option_a = []
option_b = []
option_c = []
option_d = []
correct_answer = []

# Define column names for the DataFrame
columns = ["question_id", "section_name", "question_text", "option_a", "option_b", "option_c", "option_d", "correct_answer"]

## 3. Generate English-Telugu Question Pairs

Now let's create sample questions in both languages. For each question, we'll provide:
1. English text
2. Telugu translation (separated by a newline character)

Note: In a production environment, you might use translation APIs or professional translators.

In [3]:
# Sample mathematics questions with English and Telugu translations
math_questions = [
    "If a + b = 5 and a² + b² = 13, find the value of ab.\nఒకవేళ a + b = 5 మరియు a² + b² = 13 అయితే, ab విలువను కనుగొనండి.",
    "Find the derivative of f(x) = x³ - 4x² + 7x - 2.\nf(x) = x³ - 4x² + 7x - 2 యొక్క డెరివేటివ్‌ను కనుగొనండి.",
    "Solve the equation: log₂(x) + log₂(x+3) = 3\nసమీకరణాన్ని పరిష్కరించండి: log₂(x) + log₂(x+3) = 3",
    "If the sum of the first n terms of an AP is n², find the first term and the common difference.\nఒక AP యొక్క మొదటి n పదాల మొత్తం n² అయితే, మొదటి పదం మరియు సాధారణ తేడాను కనుగొనండి.",
    "Find the area of the region bounded by the curve y = x² and the lines y = 1 and x = 2.\nవక్రరేఖ y = x² మరియు రేఖలు y = 1 మరియు x = 2 చేత పరిమితమైన ప్రాంతం యొక్క వైశాల్యాన్ని కనుగొనండి."
]

# Sample physics questions with English and Telugu translations
physics_questions = [
    "A body is projected with velocity 10 m/s at an angle 30° with the horizontal. Find the maximum height reached.\nఒక వస్తువు క్షితిజ సమాంతరంగా 30° కోణంలో 10 m/s వేగంతో ప్రక్షేపించబడింది. చేరుకున్న గరిష్ట ఎత్తును కనుగొనండి.",
    "State and explain Faraday's laws of electromagnetic induction.\nఫారడే యొక్క విద్యుదయస్కాంత ప్రేరణ నియమాలను పేర్కొని వివరించండి.",
    "What is the moment of inertia of a uniform solid sphere about its diameter?\nదాని వ్యాసం గురించి ఏకరీతి ఘన గోళం యొక్క జడత్వ క్షణం ఏమిటి?",
    "Calculate the electric field at a point due to a uniformly charged infinite plane sheet.\nఏకరీతిగా ఛార్జ్ చేయబడిన అనంత ప్లేన్ షీట్ కారణంగా ఒక బిందువు వద్ద విద్యుత్ క్షేత్రాన్ని లెక్కించండి.",
    "Explain the principle of a cyclotron with a suitable diagram.\nతగిన పటం సహాయంతో సైక్లోట్రాన్ యొక్క సూత్రాన్ని వివరించండి."
]

# Sample chemistry questions with English and Telugu translations
chemistry_questions = [
    "Define the term 'mole' in chemistry. What is Avogadro's number?\nరసాయన శాస్త్రంలో 'మోల్' అనే పదాన్ని నిర్వచించండి. అవగాడ్రో సంఖ్య ఎంత?",
    "What is the IUPAC name of CH₃-CH₂-CH₂-CH₂-OH?\nCH₃-CH₂-CH₂-CH₂-OH యొక్క IUPAC పేరు ఏమిటి?",
    "Write the electronic configuration of Fe²⁺ ion.\nFe²⁺ అయాన్ యొక్క ఎలక్ట్రానిక్ కాన్ఫిగరేషన్‌ను వ్రాయండి.",
    "Balance the following redox reaction: MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺\nఈ క్రింది రెడాక్స్ చర్యను సంతులనం చేయండి: MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺",
    "Define Hess's law of constant heat summation with an example.\nఉదాహరణతో హెస్ యొక్క నిరంతర వేడి సమ్మేశనం చట్టాన్ని నిర్వచించండి."
]

# Combine all questions
all_questions_by_section = {
    "Mathematics": math_questions,
    "Physics": physics_questions,
    "Chemistry": chemistry_questions
}

## 4. Generate English-Telugu Answer Options

Now we'll create answer options for each question in both languages. Each option will have:
1. English text
2. Telugu translation (separated by a newline character)

In [4]:
# Math answer options
math_options = [
    # Question 1
    [
        "6\n6", 
        "8\n8", 
        "9\n9", 
        "4\n4"
    ],
    # Question 2
    [
        "3x² - 8x + 7\n3x² - 8x + 7", 
        "3x² - 4x + 7\n3x² - 4x + 7", 
        "3x² - 8x\n3x² - 8x", 
        "x² - 8x + 7\nx² - 8x + 7"
    ],
    # Question 3
    [
        "x = 1\nx = 1", 
        "x = 2\nx = 2", 
        "x = 3\nx = 3", 
        "x = 4\nx = 4"
    ],
    # Question 4
    [
        "a = 1, d = 2\na = 1, d = 2", 
        "a = 2, d = 1\na = 2, d = 1", 
        "a = 0, d = 2\na = 0, d = 2", 
        "a = 1, d = 1\na = 1, d = 1"
    ],
    # Question 5
    [
        "7/3 sq. units\n7/3 చతురస్ర యూనిట్లు", 
        "8/3 sq. units\n8/3 చతురస్ర యూనిట్లు", 
        "9/3 sq. units\n9/3 చతురస్ర యూనిట్లు", 
        "10/3 sq. units\n10/3 చతురస్ర యూనిట్లు"
    ]
]

# Physics answer options
physics_options = [
    # Question 1
    [
        "1.25 m\n1.25 మీ", 
        "2.5 m\n2.5 మీ", 
        "5 m\n5 మీ", 
        "10 m\n10 మీ"
    ],
    # Question 2
    [
        "EMF is induced when magnetic flux changes\nఅయస్కాంత ప్రవాహం మారినప్పుడు EMF ప్రేరేపించబడుతుంది", 
        "EMF is proportional to the rate of change of current\nEMF కరెంట్ మార్పు రేటుకు అనుపాతంలో ఉంటుంది", 
        "Both A and B\nA మరియు B రెండూ", 
        "None of the above\nపైవేవీ కావు"
    ],
    # Question 3
    [
        "2MR²/5\n2MR²/5", 
        "2MR²/3\n2MR²/3", 
        "3MR²/10\n3MR²/10", 
        "MR²/2\nMR²/2"
    ],
    # Question 4
    [
        "E = σ/2ε₀\nE = σ/2ε₀", 
        "E = σ/ε₀\nE = σ/ε₀", 
        "E = σ/4πε₀\nE = σ/4πε₀", 
        "E = 2σ/ε₀\nE = 2σ/ε₀"
    ],
    # Question 5
    [
        "It uses magnetic field to accelerate charged particles\nఇది ఛార్జ్ చేయబడిన కణాలను వేగవంతం చేయడానికి అయస్కాంత క్షేత్రాన్ని ఉపయోగిస్తుంది", 
        "It uses electric field to accelerate charged particles\nఇది ఛార్జ్ చేయబడిన కణాలను వేగవంతం చేయడానికి విద్యుత్ క్షేత్రాన్ని ఉపయోగిస్తుంది", 
        "It uses both electric and magnetic fields\nఇది విద్యుత్ మరియు అయస్కాంత క్షేత్రాలు రెండింటినీ ఉపయోగిస్తుంది", 
        "None of the above\nపైవేవీ కావు"
    ]
]

# Chemistry answer options
chemistry_options = [
    # Question 1
    [
        "6.022 × 10²³\n6.022 × 10²³", 
        "6.022 × 10²⁴\n6.022 × 10²⁴", 
        "6.022 × 10²²\n6.022 × 10²²", 
        "6.022 × 10²¹\n6.022 × 10²¹"
    ],
    # Question 2
    [
        "Butanol\nబ్యూటనాల్", 
        "1-Butanol\n1-బ్యూటనాల్", 
        "Butyl alcohol\nబ్యూటిల్ ఆల్కహాల్", 
        "n-Butanol\nఎన్-బ్యూటనాల్"
    ],
    # Question 3
    [
        "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶\n1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶", 
        "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁴\n1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁴", 
        "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁴\n1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁴", 
        "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d⁵\n1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d⁵"
    ],
    # Question 4
    [
        "MnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O\nMnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O", 
        "2MnO₄⁻ + 5Fe²⁺ + 16H⁺ → 2Mn²⁺ + 5Fe³⁺ + 8H₂O\n2MnO₄⁻ + 5Fe²⁺ + 16H⁺ → 2Mn²⁺ + 5Fe³⁺ + 8H₂O", 
        "MnO₄⁻ + 8Fe²⁺ + 8H⁺ → Mn²⁺ + 8Fe³⁺ + 4H₂O\nMnO₄⁻ + 8Fe²⁺ + 8H⁺ → Mn²⁺ + 8Fe³⁺ + 4H₂O", 
        "None of the above\nపైవేవీ కావు"
    ],
    # Question 5
    [
        "Heat change is independent of the pathway\nవేడి మార్పు మార్గం నుండి స్వతంత్రంగా ఉంటుంది", 
        "Total heat change is always zero\nమొత్తం వేడి మార్పు ఎల్లప్పుడూ సున్నా", 
        "Heat change is directly proportional to temperature\nవేడి మార్పు ఉష్ణోగ్రతకు నేరుగా అనుపాతంలో ఉంటుంది", 
        "None of the above\nపైవేవీ కావు"
    ]
]

# Combine all options
all_options_by_section = {
    "Mathematics": math_options,
    "Physics": physics_options,
    "Chemistry": chemistry_options
}

# Define correct answers for each section
correct_answers_by_section = {
    "Mathematics": ["A", "A", "B", "D", "B"],
    "Physics": ["B", "A", "A", "A", "C"],
    "Chemistry": ["A", "B", "B", "A", "A"]
}

## 5. Combine Questions and Answers

Now let's combine all the questions, options, and correct answers into a single dataset. We'll create a pandas DataFrame with the following columns:

- `question_id`: Unique identifier for each question
- `section_name`: Mathematics, Physics, or Chemistry
- `question_text`: Bilingual question text with English and Telugu versions
- `option_a`, `option_b`, `option_c`, `option_d`: The four answer options in bilingual format
- `correct_answer`: The correct answer (A, B, C, or D)

Let's initialize empty lists to store our data:

In [5]:
# Initialize empty lists to store data
question_id = []
section_name_list = []
question_text = []
option_a = []
option_b = []
option_c = []
option_d = []
correct_answer = []

In [6]:
# Create combined dataset
q_id = 1
for section_name, questions in all_questions_by_section.items():
    for i, question in enumerate(questions):
        # Add question data
        question_id.append(q_id)
        section_name_list.append(section_name)
        question_text.append(question)
        
        # Add options
        options = all_options_by_section[section_name][i]
        option_a.append(options[0])
        option_b.append(options[1])
        option_c.append(options[2])
        option_d.append(options[3])
        
        # Add correct answer
        correct_answer.append(correct_answers_by_section[section_name][i])
        
        # Increment question ID
        q_id += 1
        
# Create DataFrame
exam_data = pd.DataFrame({
    "question_id": question_id,
    "section_name": section_name_list,
    "question_text": question_text,
    "option_a": option_a,
    "option_b": option_b,
    "option_c": option_c,
    "option_d": option_d,
    "correct_answer": correct_answer
})

# Display sample of the data
exam_data.head()

,question_id,section_name,question_text,option_a,option_b,option_c,option_d,correct_answer
0,1,Mathematics,"If a + b = 5 and a² + b² = 13, find the value ...",6\n6,8\n8,9\n9,4\n4,A
1,2,Mathematics,Find the derivative of f(x) = x³ - 4x² + 7x - ...,3x² - 8x + 7\n3x² - 8x + 7,3x² - 4x + 7\n3x² - 4x + 7,3x² - 8x\n3x² - 8x,x² - 8x + 7\nx² - 8x + 7,A
2,3,Mathematics,Solve the equation: log₂(x) + log₂(x+3) = 3\nస...,x = 1\nx = 1,x = 2\nx = 2,x = 3\nx = 3,x = 4\nx = 4,B
3,4,Mathematics,If the sum of the first n terms of an AP is n²...,"a = 1, d = 2\na = 1, d = 2","a = 2, d = 1\na = 2, d = 1","a = 0, d = 2\na = 0, d = 2","a = 1, d = 1\na = 1, d = 1",D
4,5,Mathematics,Find the area of the region bounded by the cur...,7/3 sq. units\n7/3 చతురస్ర యూనిట్లు,8/3 sq. units\n8/3 చతురస్ర యూనిట్లు,9/3 sq. units\n9/3 చతురస్ర యూనిట్లు,10/3 sq. units\n10/3 చతురస్ర యూనిట్లు,B

In [9]:
# Export to Excel file
import os
import tempfile

# Create a temporary directory for the Excel files
temp_dir = tempfile.gettempdir()
excel_file_path = os.path.join(temp_dir, 'bilingual_exam_data.xlsx')

# Create Excel writer object
with pd.ExcelWriter(excel_file_path) as writer:
    exam_data.to_excel(writer, sheet_name='Exam Data', index=False)
    
    # Auto-adjust column widths (this works with openpyxl engine)
    for column in exam_data:
        max_length = max(exam_data[column].astype(str).map(len).max(), len(column)) + 2
        col_idx = exam_data.columns.get_loc(column)
        # Apply column width adjustment
        sheet = writer.sheets['Exam Data']
        # Use openpyxl's column width adjustment
        # Handle column indices that are beyond the alphabet
        col_letter = chr(65 + col_idx) if col_idx < 26 else chr(64 + col_idx//26) + chr(65 + col_idx%26)
        sheet.column_dimensions[col_letter].width = max_length

print(f"Exam data exported to {excel_file_path} successfully!")

Exam data exported to C:\Users\polak\AppData\Local\Temp\bilingual_exam_data.xlsx successfully!

## 6. Export Data to Excel

Now that we have created our bilingual exam dataset, let's export it to an Excel file that can be used in the exam application. We'll use the `ExcelWriter` from pandas with openpyxl to create a well-formatted Excel file with appropriate column widths.

In [10]:
# Function to split bilingual content for display
def split_bilingual_content(dataframe, column_name):
    """Split bilingual content into separate English and Telugu columns for display purposes"""
    english_texts = []
    telugu_texts = []
    
    for content in dataframe[column_name]:
        parts = content.split('\n\n')
        if len(parts) >= 2:
            english_texts.append(parts[0])
            telugu_texts.append(parts[1])
        else:
            english_texts.append(content)
            telugu_texts.append("")
    
    return english_texts, telugu_texts

# Create a display version of the dataframe with separated columns
display_df = exam_data.copy()

# Split question text
english_questions, telugu_questions = split_bilingual_content(display_df, 'question_text')
display_df['question_english'] = english_questions
display_df['question_telugu'] = telugu_questions

# Display the first few rows with separated columns
display_df[['question_id', 'section_name', 'question_english', 'question_telugu']].head()

,question_id,section_name,question_english,question_telugu
0,1,Mathematics,"If a + b = 5 and a² + b² = 13, find the value ...",
1,2,Mathematics,Find the derivative of f(x) = x³ - 4x² + 7x - ...,
2,3,Mathematics,Solve the equation: log₂(x) + log₂(x+3) = 3\nస...,
3,4,Mathematics,If the sum of the first n terms of an AP is n²...,
4,5,Mathematics,Find the area of the region bounded by the cur...,

## 7. Summary

In this notebook, we've accomplished the following:

1. Created a bilingual dataset with questions and answers in both English and Telugu
2. Organized questions into three sections: Mathematics, Physics, and Chemistry
3. Added four options for each question with the correct answer marked
4. Combined all data into a structured DataFrame
5. Exported the data to an Excel file for use in the exam application

The bilingual format uses a double newline (`\n\n`) to separate the English and Telugu versions of each question and answer option. This format makes it easy to display the appropriate language in the exam interface based on user selection.

The generated Excel file can be imported into the exam system to provide bilingual content to students taking the EAMCET exams.

In [11]:
# Additional Export: Create separate view sheets with split columns
import os
import tempfile

# Create a temporary directory for the Excel files
temp_dir = tempfile.gettempdir()
split_view_path = os.path.join(temp_dir, 'bilingual_exam_data_split_view.xlsx')

with pd.ExcelWriter(split_view_path) as writer:
    # Export main data
    exam_data.to_excel(writer, sheet_name='Combined Data', index=False)
    
    # Create display dataframe with separate language columns
    view_df = exam_data.copy()
    
    # Split all bilingual columns
    for column in ['question_text', 'option_a', 'option_b', 'option_c', 'option_d']:
        english_texts, telugu_texts = split_bilingual_content(view_df, column)
        view_df[f"{column}_english"] = english_texts
        view_df[f"{column}_telugu"] = telugu_texts
    
    # Export the view with split columns
    columns_to_export = ['question_id', 'section_name', 
                         'question_text_english', 'question_text_telugu',
                         'option_a_english', 'option_a_telugu',
                         'option_b_english', 'option_b_telugu',
                         'option_c_english', 'option_c_telugu',
                         'option_d_english', 'option_d_telugu',
                         'correct_answer']
    
    view_df[columns_to_export].to_excel(writer, sheet_name='Split View', index=False)
    
    # Create section-specific sheets
    for section in ['Mathematics', 'Physics', 'Chemistry']:
        section_data = view_df[view_df['section_name'] == section]
        section_data[columns_to_export].to_excel(writer, sheet_name=section, index=False)
    
    # Auto-adjust column widths for all sheets using openpyxl method
    for sheet_name in writer.sheets:
        sheet = writer.sheets[sheet_name]
        for i, column in enumerate(columns_to_export[:min(len(columns_to_export), 20)]):  # Limit to 20 columns for performance
            # Apply a reasonable default width
            col_letter = chr(65 + i) if i < 26 else chr(64 + i//26) + chr(65 + i%26)
            sheet.column_dimensions[col_letter].width = 20  # Standard width

print(f"Split view export completed to {split_view_path}")

Split view export completed to C:\Users\polak\AppData\Local\Temp\bilingual_exam_data_split_view.xlsx